version: "3.8"

services:
  app:
    build: .
    container_name: car-rental-app
    ports:
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-Dh2.webAllowOthers=true
    restart: unless-stopped
